### ISSUE TITLE
Iterate over specific columns but all the rows, check if the entry is an ip address only then proceed

### ISSUE THREAD

**Issue by achoudh5** [achoudh5/Manipulating_Excel_Sheet#1]

**Comment by achoudh5** [comment]
**Update:-** **I have added a sample excel sheet with Column A,B,C**
Task:-
Ex. Iterate over Column A and C from row-> 1 to 100 & skip column B. 
Entries in rows would be like 4.4.4.4 or a text like abcd, the cell value should only be read when it's 4.4.4.4 and pass when it's a text
Use language: python and module: openpyxl
Take an example excel sheet yourself if you want to.

**Comment by aparharsh** [comment]
Hey,
I have experience in working with python and its modules.
Can you assign this issue to me?

**Comment by achoudh5** [comment]
sure @aparharsh

**Comment by aparharsh** [comment]
Can we connect on some platform? For eg., on Gmail?
So that I can get some more details about the task.
I was not able to get your email id on your profile, so can you either give me your mail id or mail on mine?

**Comment by achoudh5** [comment]
I would prefer to use this issue thread @aparharsh if that's fine by you. I would be happy to answer any doubts you might have for the issue. Another reason being your doubt might help other people as well :)

**Comment by aparharsh** [comment]
I have a few doubts.
Will i be given the column names which must be iterated? Or, there will be always two columns, A and C.
Only those rows must be considered for the further code whose columns A and C both, must be containing a string of format 1.2.3.4 ?
Which cell values must be read, if both A and C contains the format 1.2.3.4 ?

**Comment by achoudh5** [comment]
Good Question @aparharsh !

- You will always have column name but if you can do without using them it would be superb 💯 

- Yes, you will iterate over columns A and C. If the format is like an IP address ex. 1.2.3.4 only then read it (you can use regex) else don't read that value and move to next value. 
_Note:_1.2.3.4 is just an example format, ip address values are not hard coded. It should be an ip address, that's important

**Comment by aparharsh** [comment]
I wrote the code, along with proper comments explaining the whole code.
Can you review it ?
