### ISSUE TITLE
Clean code in zip.py

### ISSUE THREAD

**Issue by achoudh5** [achoudh5/Manipulating_Excel_Sheet#13]
- Use OOP concepts

- Clean the code

- Reduce the length of code

- Optimize the code

- DRY (Don't Repeat Yourself)

**Comment by wevnasc** [comment]
@achoudh5 could you assign this task to me?

**Comment by saisiddhant12** [comment]
@achoudh5 I would like to give this a shot.

**Comment by achoudh5** [comment]
@saisiddhant12 please go ahead 😀

**Comment by saisiddhant12** [comment]
Pull Request#31 

- [ ] Create a config file for usage of all hardcoded value
- [ ] Develop a blue print for applying OOP & get a sign off
- [ ] Re-iterate the blueprint post feedback
- [ ] Make the blocks more modular by introducing more set of user defined functions
